// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_News.Models;

#nullable disable

namespace Web_News.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240813065845_PasswordHasher")]
    partial class PasswordHasher
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Web_News.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("Describe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameRole")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            Describe = "Administrator Role",
                            NameRole = "Admin"
                        },
                        new
                        {
                            RoleID = 2,
                            Describe = "Customer Role",
                            NameRole = "User"
                        });
                });

            modelBuilder.Entity("Web_News.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserID = 1,
                            Email = "admin@gmail.com",
                            Name = "Administrator",
                            Password = "jGl25bVBBBW96Qi9Te4V37Fnqchz/Eu4qB9vKrRIqRg=",
                            RegistrationDate = new DateTime(2024, 8, 13, 13, 58, 43, 851, DateTimeKind.Local).AddTicks(9087),
                            UserName = "admin"
                        },
                        new
                        {
                            UserID = 2,
                            Email = "hngoctro@gmail.com",
                            Name = "Huỳnh Ngọc Trợ",
                            Password = "71EwYhTZpjYe4dW0UubSu3DcfruFv54Cw9R0f7V9a+w=",
                            RegistrationDate = new DateTime(2024, 8, 13, 13, 58, 43, 851, DateTimeKind.Local).AddTicks(9115),
                            UserName = "NgocTro"
                        },
                        new
                        {
                            UserID = 3,
                            Email = "phucbin366@gmail.com",
                            Name = "Trần Văn Phúc",
                            Password = "71EwYhTZpjYe4dW0UubSu3DcfruFv54Cw9R0f7V9a+w=",
                            RegistrationDate = new DateTime(2024, 8, 13, 13, 58, 43, 851, DateTimeKind.Local).AddTicks(9131),
                            UserName = "VanPhuc"
                        },
                        new
                        {
                            UserID = 4,
                            Email = "caothiphuongvy27@gmail.com",
                            Name = "Cao Thị Phương Vy",
                            Password = "71EwYhTZpjYe4dW0UubSu3DcfruFv54Cw9R0f7V9a+w=",
                            RegistrationDate = new DateTime(2024, 8, 13, 13, 58, 43, 851, DateTimeKind.Local).AddTicks(9145),
                            UserName = "PhuongVy"
                        },
                        new
                        {
                            UserID = 5,
                            Email = "nguyenngocquy182752@gmail.com",
                            Name = "Nguyễn Thị Ngọc Quý",
                            Password = "71EwYhTZpjYe4dW0UubSu3DcfruFv54Cw9R0f7V9a+w=",
                            RegistrationDate = new DateTime(2024, 8, 13, 13, 58, 43, 851, DateTimeKind.Local).AddTicks(9160),
                            UserName = "NgocQuy"
                        });
                });

            modelBuilder.Entity("Web_News.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 2
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Web_News.Models.UserRole", b =>
                {
                    b.HasOne("Web_News.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Web_News.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Web_News.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("Web_News.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
